ELECTORAL_NUMBERS = [{'state': 'Alabama', 'state_abbr': 'AL', 'votes': 9},
 {'state': 'Kentucky', 'state_abbr': 'KY', 'votes': 8},
 {'state': 'North Dakota', 'state_abbr': 'ND', 'votes': 3},
 {'state': 'Alaska', 'state_abbr': 'AK', 'votes': 3},
 {'state': 'Louisiana', 'state_abbr': 'LA', 'votes': 8},
 {'state': 'Ohio', 'state_abbr': 'OH', 'votes': 17},
 {'state': 'Arizona', 'state_abbr': 'AZ', 'votes': 11},
 {'state': 'Maine', 'state_abbr': 'ME', 'votes': 4},
 {'state': 'Oklahoma', 'state_abbr': 'OK', 'votes': 7},
 {'state': 'Arkansas', 'state_abbr': 'AR', 'votes': 6},
 {'state': 'Maryland', 'state_abbr': 'MD', 'votes': 10},
 {'state': 'Oregon', 'state_abbr': 'OR', 'votes': 8},
 {'state': 'California', 'state_abbr': 'CA', 'votes': 54},
 {'state': 'Massachusetts', 'state_abbr': 'MA', 'votes': 11},
 {'state': 'Pennsylvania', 'state_abbr': 'PA', 'votes': 19},
 {'state': 'Colorado', 'state_abbr': 'CO', 'votes': 10},
 {'state': 'Michigan', 'state_abbr': 'MI', 'votes': 15},
 {'state': 'Rhode Island', 'state_abbr': 'RI', 'votes': 4},
 {'state': 'Connecticut', 'state_abbr': 'CT', 'votes': 7},
 {'state': 'Minnesota', 'state_abbr': 'MN', 'votes': 10},
 {'state': 'South Carolina', 'state_abbr': 'SC', 'votes': 9},
 {'state': 'Delaware', 'state_abbr': 'DE', 'votes': 3},
 {'state': 'Mississippi', 'state_abbr': 'MS', 'votes': 6},
 {'state': 'South Dakota', 'state_abbr': 'SD', 'votes': 3},
 {'state': 'District of Columbia', 'state_abbr': 'DC', 'votes': 3},
 {'state': 'Missouri', 'state_abbr': 'MO', 'votes': 10},
 {'state': 'Tennessee', 'state_abbr': 'TN', 'votes': 11},
 {'state': 'Florida', 'state_abbr': 'FL', 'votes': 30},
 {'state': 'Montana', 'state_abbr': 'MT', 'votes': 4},
 {'state': 'Texas', 'state_abbr': 'TX', 'votes': 40},
 {'state': 'Georgia', 'state_abbr': 'GA', 'votes': 16},
 {'state': 'Nebraska', 'state_abbr': 'NE', 'votes': 5},
 {'state': 'Utah', 'state_abbr': 'UT', 'votes': 6},
 {'state': 'Hawaii', 'state_abbr': 'HI', 'votes': 4},
 {'state': 'Nevada', 'state_abbr': 'NV', 'votes': 6},
 {'state': 'Vermont', 'state_abbr': 'VT', 'votes': 3},
 {'state': 'Idaho', 'state_abbr': 'ID', 'votes': 4},
 {'state': 'New Hampshire', 'state_abbr': 'NH', 'votes': 4},
 {'state': 'Virginia', 'state_abbr': 'VA', 'votes': 13},
 {'state': 'Illinois', 'state_abbr': 'IL', 'votes': 19},
 {'state': 'New Jersey', 'state_abbr': 'NJ', 'votes': 14},
 {'state': 'Washington', 'state_abbr': 'WA', 'votes': 12},
 {'state': 'Indiana', 'state_abbr': 'IN', 'votes': 11},
 {'state': 'New Mexico', 'state_abbr': 'NM', 'votes': 5},
 {'state': 'West Virginia', 'state_abbr': 'WV', 'votes': 4},
 {'state': 'Iowa', 'state_abbr': 'IA', 'votes': 6},
 {'state': 'New York', 'state_abbr': 'NY', 'votes': 28},
 {'state': 'Wisconsin', 'state_abbr': 'WI', 'votes': 10},
 {'state': 'Kansas', 'state_abbr': 'KS', 'votes': 6},
 {'state': 'North Carolina', 'state_abbr': 'NC', 'votes': 16},
 {'state': 'Wyoming', 'state_abbr': 'WY', 'votes': 3}]

STATE_ABBREVIATIONS = {
    'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA',
    'Colorado': 'CO', 'Connecticut': 'CT', 'Delaware': 'DE', 'Florida': 'FL', 'Georgia': 'GA',
    'Hawaii': 'HI', 'Idaho': 'ID', 'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA',
    'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA', 'Maine': 'ME', 'Maryland': 'MD',
    'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS', 'Missouri': 'MO',
    'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
    'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH',
    'Oklahoma': 'OK', 'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
    'South Dakota': 'SD', 'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT',
    'Virginia': 'VA', 'Washington': 'WA', 'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY',
    'District of Columbia': 'DC' # DC is treated like a State for purposes of the Electoral College 
}